// <auto-generated />
using System;
using Employee.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Employee.Infrastructure.Data.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    partial class EmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Employee.Core.Models.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("area_id");

                    b.Property<short>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("AreaId");

                    b.HasIndex("Active")
                        .HasDatabaseName("idx_area_active");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_area_name");

                    b.ToTable("area", (string)null);
                });

            modelBuilder.Entity("Employee.Core.Models.Backup", b =>
                {
                    b.Property<int>("BackupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("backup_id");

                    b.Property<string>("BackupName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("backup_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("LONGTEXT")
                        .HasColumnName("data_json");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ExcelFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("excel_file_name");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("restored_at");

                    b.HasKey("BackupId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_backup_created_at");

                    b.ToTable("backup", (string)null);
                });

            modelBuilder.Entity("Employee.Core.Models.Daily", b =>
                {
                    b.Property<int>("DailyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("daily_id");

                    b.Property<string>("AreaName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("area_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("Fullname")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("fullname");

                    b.Property<short>("SkillLv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("skill_lv");

                    b.Property<string>("SkillNote")
                        .HasColumnType("text")
                        .HasColumnName("skill_note");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("TimeTest")
                        .HasColumnType("datetime")
                        .HasColumnName("time_test");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<TimeOnly?>("WorkEnd")
                        .HasColumnType("TIME")
                        .HasColumnName("work_end");

                    b.Property<TimeOnly?>("WorkStart")
                        .HasColumnType("TIME")
                        .HasColumnName("work_start");

                    b.HasKey("DailyId");

                    b.HasIndex("Day")
                        .HasDatabaseName("idx_daily_day");

                    b.HasIndex("EmployeeId", "Day")
                        .IsUnique()
                        .HasDatabaseName("uk_daily_employee_day");

                    b.ToTable("daily", (string)null);
                });

            modelBuilder.Entity("Employee.Core.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<short>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("active");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("area_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Fullname")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("fullname");

                    b.Property<string>("FullnameOther")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("fullname_other");

                    b.Property<int>("LeaveDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("leave_days");

                    b.Property<int>("NightShiftDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("night_shift_days");

                    b.Property<int>("PermissionGranted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("permission_granted");

                    b.Property<string>("PlantName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("plant_name");

                    b.Property<string>("Sale")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sale");

                    b.Property<short>("SkillLv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("skill_lv");

                    b.Property<string>("SkillNote")
                        .HasColumnType("text")
                        .HasColumnName("skill_note");

                    b.Property<DateTime?>("TimeTest")
                        .HasColumnType("datetime")
                        .HasColumnName("time_test");

                    b.Property<int>("TotalDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_days");

                    b.Property<int>("TrainingDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("training_days");

                    b.Property<int>("TravelDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("travel_days");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<int>("UnauthorizedLeave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("unauthorized_leave");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<int>("VisaExtension")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("visa_extension");

                    b.Property<int>("WorkDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("work_days");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Active")
                        .HasDatabaseName("idx_employee_active");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("idx_employee_area");

                    b.HasIndex("Fullname")
                        .HasDatabaseName("idx_employee_fullname");

                    b.HasIndex("FullnameOther")
                        .HasDatabaseName("idx_employee_fullname_other");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_employee_type");

                    b.ToTable("employee", (string)null);
                });

            modelBuilder.Entity("Employee.Core.Models.EmployeeProject", b =>
                {
                    b.Property<int>("EmployeeProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_project_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.HasKey("EmployeeProjectId");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("idx_employee_project_employee");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_employee_project_project");

                    b.HasIndex("EmployeeId", "ProjectId")
                        .IsUnique()
                        .HasDatabaseName("uk_employee_project");

                    b.ToTable("employee_project", (string)null);
                });

            modelBuilder.Entity("Employee.Core.Models.Excel", b =>
                {
                    b.Property<int>("ExcelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("excel_id");

                    b.Property<string>("ExcelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("excel_name");

                    b.Property<DateTime>("TimeUpload")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("time_upload")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ExcelId");

                    b.ToTable("excel", (string)null);
                });

            modelBuilder.Entity("Employee.Core.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("feedback_id");

                    b.Property<string>("AdminResponse")
                        .HasColumnType("TEXT")
                        .HasColumnName("admin_response");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("responded_at");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2)
                        .HasColumnName("status");

                    b.Property<short?>("StatusResponse")
                        .HasColumnType("smallint")
                        .HasColumnName("status_response");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("TimesheetId")
                        .HasColumnType("int")
                        .HasColumnName("timesheet_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("FeedbackId");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("idx_feedback_employee");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_feedback_status");

                    b.HasIndex("TimesheetId")
                        .HasDatabaseName("idx_feedback_timesheet");

                    b.ToTable("feedback", (string)null);
                });

            modelBuilder.Entity("Employee.Core.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("project_code");

                    b.Property<string>("ProjectDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("project_description");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("project_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("ProjectId");

                    b.HasIndex("ProjectCode")
                        .IsUnique()
                        .HasDatabaseName("uk_project_code");

                    b.HasIndex("ProjectName")
                        .HasDatabaseName("idx_project_name");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("Employee.Core.Models.ProjectMonth", b =>
                {
                    b.Property<int>("ProjectMonthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("project_month_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date")
                        .HasColumnName("month");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.HasKey("ProjectMonthId");

                    b.HasIndex("Month")
                        .HasDatabaseName("idx_project_month_month");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_project_month_project");

                    b.HasIndex("EmployeeId", "ProjectId", "Month")
                        .IsUnique()
                        .HasDatabaseName("uk_project_month_emp");

                    b.ToTable("project_month", (string)null);
                });

            modelBuilder.Entity("Employee.Core.Models.Timesheet", b =>
                {
                    b.Property<int>("TimesheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("timesheet_id");

                    b.Property<string>("AbsenceReason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("absence_reason");

                    b.Property<short?>("AbsenceType")
                        .HasColumnType("smallint")
                        .HasColumnName("absence_type");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("area_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<byte?>("DayOfWeek")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("day_of_week");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("notes");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<TimeOnly?>("WorkEnd")
                        .HasColumnType("TIME")
                        .HasColumnName("work_end");

                    b.Property<TimeOnly?>("WorkStart")
                        .HasColumnType("TIME")
                        .HasColumnName("work_start");

                    b.HasKey("TimesheetId");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("idx_timesheet_area");

                    b.HasIndex("Day")
                        .HasDatabaseName("idx_timesheet_day");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_timesheet_status");

                    b.HasIndex("EmployeeId", "Day")
                        .IsUnique()
                        .HasDatabaseName("uk_timesheet_employee_day");

                    b.ToTable("timesheet", (string)null);
                });

            modelBuilder.Entity("Employee.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<short>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<short>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2)
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Active")
                        .HasDatabaseName("idx_user_active");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("fk_user_employee_idx");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uk_user_username");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Employee.Core.Models.Daily", b =>
                {
                    b.HasOne("Employee.Core.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Employee.Core.Models.Employee", b =>
                {
                    b.HasOne("Employee.Core.Models.Area", "Area")
                        .WithMany("Employees")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Employee.Core.Models.EmployeeProject", b =>
                {
                    b.HasOne("Employee.Core.Models.Employee", "Employee")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Employee.Core.Models.Project", "Project")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Employee.Core.Models.Feedback", b =>
                {
                    b.HasOne("Employee.Core.Models.Employee", "Employee")
                        .WithMany("Feedbacks")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Employee.Core.Models.Timesheet", "Timesheet")
                        .WithMany("Feedbacks")
                        .HasForeignKey("TimesheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Timesheet");
                });

            modelBuilder.Entity("Employee.Core.Models.ProjectMonth", b =>
                {
                    b.HasOne("Employee.Core.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Employee.Core.Models.Project", "Project")
                        .WithMany("ProjectMonths")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Employee.Core.Models.Timesheet", b =>
                {
                    b.HasOne("Employee.Core.Models.Area", "Area")
                        .WithMany("Timesheets")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Employee.Core.Models.Employee", "Employee")
                        .WithMany("Timesheets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Employee.Core.Models.User", b =>
                {
                    b.HasOne("Employee.Core.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Employee.Core.Models.Area", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Timesheets");
                });

            modelBuilder.Entity("Employee.Core.Models.Employee", b =>
                {
                    b.Navigation("EmployeeProjects");

                    b.Navigation("Feedbacks");

                    b.Navigation("Timesheets");
                });

            modelBuilder.Entity("Employee.Core.Models.Project", b =>
                {
                    b.Navigation("EmployeeProjects");

                    b.Navigation("ProjectMonths");
                });

            modelBuilder.Entity("Employee.Core.Models.Timesheet", b =>
                {
                    b.Navigation("Feedbacks");
                });
#pragma warning restore 612, 618
        }
    }
}
